version: '3.8'

services:
  app:
    build: ./
    container_name: app
    image: node-app
    env_file: ./.env
    ports:
      - '3001:3001'
    environment:
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    depends_on:
      - database
      - redis
    volumes:
      - .:/app
    networks:
      - node-network

  database:
    image: mysql:8
    container_name: database
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db:/var/lib/mysql
    networks:
      - node-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - node-network

volumes:
  db:

networks:
  node-network:
    driver: bridge