version: '3.8'

services:
  wallet_app:
    build: ./
    container_name: wallet_app
    image: node-app
    env_file: ./.env
    ports:
      - '3001:3001'
    environment:
      - APP_PORT=$APP_PORT
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
    depends_on:
      - wallet_db
      - wallet_redis
    volumes:
      - .:/app
    networks:
      - node-network

  wallet_db:
    image: mysql:8
    container_name: wallet_db
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '3309:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    volumes:
      - db:/var/lib/mysql
    networks:
      - node-network

  wallet_redis:
    image: redis
    container_name: wallet_redis
    ports:
      - "6379:6379"
    networks:
      - node-network

volumes:
  db:

networks:
  node-network:
    driver: bridge