version: '3.8'

services:

  wallet_db:
    image : mysql
    container_name : wallet_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./usr/src/app/db_data:/var/lib/mysql

  wallet_app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3002"
    working_dir: /usr/src/app
    depends_on:
      - db